import './globals.css';
import type { Metadata } from 'next';
import { hidayatullahFont, lateef, source_sans_3 } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Quran',
  description: 'Generated by Greentech apps limited',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${source_sans_3.variable} ${hidayatullahFont.variable} ${lateef.variable} h-screen w-full font-source_sans_3 text-neutral-900`}
      >
        {children}
      </body>
    </html>
  );
}
